gems: [jekyll-paginate]

# Site settings
title: DJ lemon-Sour's diary (prod.hisasann)
email: ""
description: > # this means to ignore newlines until "baseurl:"
  DJ lemon-Sour's diary (prod.hisasann)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hisasann.github.io/" # the base hostname & protocol for your site
twitter_username: hisasann
github_username:  hisasann
repository: hisasann/hisasann.github.io

timezone: Asia/Tokyo
encoding: utf-8

paginate: 10
paginate_path: "page/:num"
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]

exclude: [vendor]