# Site settings
title: DJレモンサワーのレモン日記
email: ""
description: > # this means to ignore newlines until "baseurl:"
  レモンサワーとプログラムの日記
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hisasann.com" # the base hostname & protocol for your site
twitter_username: hisasann
github_username:  hisasann

timezone: Asia/Tokyo
encoding: utf-8

paginate: 10
paginate_path: "page/:num"
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

exclude: [vendor]